### ISSUE TITLE
api key

### ISSUE THREAD

**Issue by sasherafat** [domnguyen/Discord-Bot#18]
hi dude
what is api key and how can i got it?

**Comment by SebastianDang** [comment]
Hi Seyed,

The config variable ApiKey is used for specific apis that other services are using. I believe you can ignore this configuration.

The config variable DiscordToken is used for connecting to the specified bot. You can find more information on how to set up a bot and get your token here:

https://discord.com/developers/docs/topics/oauth2#bots
